// Copyright © 2026 Lucia Medina Fretes. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for details.
/// Resource ID constants — mirrors Res.swift exactly.
export const Res = {

    // Strings
    STR_SDL_INIT_FALLO:                    0,
    STR_WINDOW_CAPTION:                    1,
    STR_FATAL_ERROR_CAPTION:               2,
    STR_PRESIONE_PARA_CONTINUAR:           3,
    STR_CARGANDO:                          4,
    STR_SIGUIENTE:                         5,
    STR_ATRAS:                             6,
    STR_GANASTE:                           7,
    STR_PERDISTE:                          8,
    STR_CONTINUARJUEGO:                    9,
    STR_OBJETIVOS:                         10,
    STR_ACEPTAR:                           11,
    STR_CONTINUAR:                         12,
    STR_MENU_PRINCIPAL:                    13,
    STR_MENU_CONTINUAR:                    14,
    STR_MENU_NUEVO_JUEGO:                  15,
    STR_MENU_CARGAR_PARTIDA:               16,
    STR_MENU_OPCIONES:                     17,
    STR_MENU_CREDITOS:                     18,
    STR_MENU_AYUDA:                        19,
    STR_MENU_SALIR:                        20,
    STR_MENU_GUARDAR:                      21,
    STR_MENU_REINICIAR:                    22,
    STR_BOTON_MENU:                        23,
    STR_BOTON_MENU_DEL_JUEGO:              24,
    STR_JUEGO_PAUSADO:                     25,
    STR_UNIDAD:                            26,
    STR_PUNTOS_DE_RESISTENCIA:             27,
    STR_ALCANCE:                           28,
    STR_PUNTOS_DE_ATAQUE:                  29,
    STR_VISIBILIDAD:                       30,
    STR_PUNTERIA:                          31,
    STR_VELOCIDAD:                         32,
    STR_CONFIRMACION_SALIR:                33,
    STR_SI:                                34,
    STR_NO:                                35,
    STR_INGRESE_NOMBRE:                    36,
    STR_LISTO:                             37,
    STR_CREDITOS_PROGRAMACION:             38,
    STR_CREDITOS_PROGRAMADOR_1:            39,
    STR_CREDITOS_DISENO_DE_NIVEL:          40,
    STR_CREDITOS_DISENADOR_DE_NIVEL_1:     41,
    STR_OBJETIVO_BATALLA_1_1:              42,
    STR_OBJETIVO_BATALLA_2_1:              43,
    STR_OBJETIVO_BATALLA_3_1:              44,
    STR_OBJETIVO_BATALLA_4_1:              45,
    STR_PRIMER_BATALLA:                    46,
    STR_PRIMER_BATALLA_2:                  47,
    STR_PRIMER_BATALLA_OBJETIVO_3:         48,
    STR_SEGUNDA_BATALLA:                   49,
    STR_SEGUNDA_BATALLA_2:                 50,
    STR_SEGUNDA_BATALLA_OBJETIVO_3:        51,
    STR_TERCER_BATALLA:                    52,
    STR_TERCER_BATALLA_2:                  53,
    STR_TERCER_BATALLA_OBJETIVO_3:         54,
    STR_CUARTA_BATALLA:                    55,
    STR_CUARTA_BATALLA_2:                  56,
    STR_CUARTA_BATALLA_OBJETIVO_3:         57,
    STR_CONSECUENCIAS:                     58,
    STR_CONSECUENCIAS_1:                   59,
    STR_CONSECUENCIAS_2:                   60,
    STR_CONSECUENCIAS_3:                   61,
    STR_MENU_AYUDA_TEXTO_SELECCIONAR_01:   62,
    STR_MENU_AYUDA_TEXTO_SELECCIONAR_02:   63,
    STR_MENU_AYUDA_TEXTO_MOVER_01:         64,
    STR_MENU_AYUDA_TEXTO_MOVER_02:         65,
    STR_MENU_AYUDA_TEXTO_ATACAR_01:        66,
    STR_MENU_AYUDA_TEXTO_ATACAR_02:        67,
    STR_MENU_AYUDA_TEXTO_OBJETIVO_01:      68,
    STR_MENU_AYUDA_TEXTO_OBJETIVO_02:      69,
    STR_MENU_AYUDA_TEXTO_SCROLL_01:        70,
    STR_MENU_AYUDA_TEXTO_SCROLL_02:        71,
    STR_MENU_AYUDA_TEXTO_HUD_01:           72,
    STR_MENU_AYUDA_TEXTO_HUD_02:           73,
    STR_MENU_AYUDA_TEXTO_SANAR_01:         74,
    STR_MENU_AYUDA_TEXTO_SANAR_02:         75,
    STR_MENU_AYUDA_TEXTO_TIPS_01:          76,
    STR_MENU_AYUDA_TEXTO_TIPS_02:          77,
    STR_MENU_AYUDA_TEXTO_GANAR_01:         78,
    STR_MENU_AYUDA_TEXTO_GANAR_02:         79,
    STR_TIP_00:         80,   // "Tip!" button label
    STR_LANGUAGE:       81,
    STR_LANGUAGE_LABEL: 82,
    STR_COUNT:          83,

    // Fonts
    FNT_SANS:   0,
    FNT_LBLACK: 1,
    FNT_COUNT:  2,

    // Tilesets
    TLS_DEBUG:      0,  TLS_PASTO:    1,  TLS_TIERRA:    2,
    TLS_AGUA:       3,  TLS_ARBOLES:  4,  TLS_UNIDADES:  5,
    TLS_PIEDRAS:    6,  TLS_TEXTURAS: 7,  TLS_PIEDRAS2:  8,
    TLS_ENFERMERIA: 9,  TLS_EDIFICIOS: 10, TLS_INVALIDADO: 11,
    TLS_OBJETIVOS: 12,  TLS_FUERTE:  13,  TLS_COUNT:     14,

    MAP_NIVEL1: 14,
    MAP_COUNT:  1,

    // Sounds
    SFX_SPLASH:           0,
    SFX_DISPARO_PATRICIO: 1,
    SFX_DISPARO_INGLES:   2,
    SFX_MUERTE_PATRICIO:  3,
    SFX_BATALLA:          4,
    SFX_COUNT:            5,

    // Images
    IMG_CURSOR_ESPADA:    0,
    IMG_CURSOR_ENFERMERIA: 1,
    IMG_CURSOR:           2,
    IMG_FLECHA:           3,
    IMG_ICONO:            4,
    IMG_LOGO:             5,
    IMG_SPLASH:           6,
    IMG_FONDO:            7,
    IMG_TILE_GRIS:        8,
    IMG_HUD:              9,
    IMG_COUNT:            10,

    // Unit types
    UNIDAD_PATRICIO: 0,
    UNIDAD_INGLES:   1,
    UNIDAD_COUNT:    2,

    // Sprites
    SPR_PATRICIO: 0,
    SPR_INGLES:   1,
    SPR_COUNT:    2,

    // Animations
    ANIM_AROS:            0,
    ANIM_FLECHA_GUIA:     1,
    ANIM_FUEGO_1:         2,
    ANIM_FUEGO_2:         3,
    ANIM_AYUDA_SELECCION: 4,
    ANIM_AYUDA_MOVER:     5,
    ANIM_AYUDA_ATACAR:    6,
    ANIM_AYUDA_OBJETIVO:  7,
    ANIM_AYUDA_SCROLL:    8,
    ANIM_AYUDA_HUD:       9,
    ANIM_AYUDA_SANAR:     10,
    ANIM_AYUDA_TIPS:      11,
    ANIM_AYUDA_GANAR:     12,
    ANIM_COUNT:           13,

    // Sprite animation indices (within each Sprite's cumulative animation count)
    // Each animpak has 8 rows (one per compass direction).
    SPR_ANIM_PATRICIO_QUIETO_N: 0,
    SPR_ANIM_PATRICIO_CAMINA_N: 8,
    SPR_ANIM_PATRICIO_MUERE_N:  16,
    SPR_ANIM_PATRICIO_ATACA_N:  24,
    SPR_ANIM_INGLES_QUIETO_N:   0,
    SPR_ANIM_INGLES_CAMINA_N:   8,
    SPR_ANIM_INGLES_MUERE_N:    16,
    SPR_ANIM_INGLES_ATACA_N:    24,

    // Tiles
    TILE_DEBUG_ID_TILES_VECINOS:      0,
    TILE_DEBUG_ID_TILE_CHICO:         1,
    TILE_DEBUG_ID_TILE_CHICO_VECINOS: 2,
    TILE_DEBUG_ID_CAMINO_A_SEGUIR:    3,
    TILE_DEBUG_ID_TILE_CHICO_GRIS:    4,
    TILE_UNIDADES_ID_PATRICIO:        0,
    TILE_UNIDADES_ID_INGLES:          1,
    TILE_INVALIDADOS_ID_ENFERMERIA:   0,
    TILE_INVALIDADOS_ID_CASA:         1,
    TILE_OBJETIVOS_ID_MOVER:          0,
    TILE_OBJETIVOS_ID_ATACAR:         1,
} as const
